# Project information
site_name: iCF
# defeine TOC or order of website-
nav:
  - Home: index.md
  - how-it-works?: how-it-works.md
  - General Guidelines: 
  - Rules and Regulations: rules.md 
  - FAQ: faq.md
  - Feedback: feedback.md

site_author: iNeuron.ai
site_description: >-
  DESCRIPTION

# Repository
repo_name: iNeuron-Pvt-Ltd/iCF
repo_url: https://github.com/iNeuron-Pvt-Ltd/iCF

# Configuration
theme:
  name: material
  features:
    - tabs
  language: en
  palette:
    primary: green
    accent: green

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/iNeuron-Pvt-Ltd
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight

copyright: |
  &copy; 2021 <a href="https://github.com/iNeuron-Pvt-Ltd"  target="_blank" rel="noopener">iNeuron.ai</a>
