# Project information
site_name: iCF
# define TOC or order of website-
nav:
  - Home: index.md
  - How-it-works?: how-it-works.md
  - Guidelines: 
      - General guidelines: guidelines.md
      - Should I Submit an Application to the ICF?: Should I Submit an Application to the ICF.md
      - The Coding Begins: The Coding Begins.md
      - How to Get a Head Start in ICF?: How to Get a Head Start in ICF.md
      - Managing Time for Students: Managing Time for Students.md
      - Criteria for Evaluation: Criteria for Evaluation.md
  - Proposal template: pro-template.md
  - Rules and Regulations: rules.md 
  - FAQ: faq.md
  - Feedback: feedback.md

site_author: iNeuron.ai
site_description: >-
  DESCRIPTION

# Repository
repo_name: iNeuron-Pvt-Ltd/iCF
repo_url: https://github.com/iNeuron-Pvt-Ltd/iCF

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
  language: en
  palette:
    scheme: slate
    primary: green
    accent: green
  logo: assets/mainLogo.jpg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/iNeuron-Pvt-Ltd
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iNeuronAi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ineuron-ai/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ineuron.ai/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/ineuronintelligence
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ineuronai

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  - attr_list
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search

copyright: |
  &copy; 2021 <a href="https://github.com/iNeuron-Pvt-Ltd"  target="_blank" rel="noopener">iNeuron.ai</a>

